#!/bin/bash
while [[ ! "$yesnowifi" =~ ^[yYnN]$ ]]; do read -n1 -p "Do you want to connect to wifi? [y/n] : " yesnowifi && echo; done
case $yesnowifi in
	y|Y)
		echo "[ CONNECT TO WIFI ]"
		nmcli device wifi list
		echo
		read -p "Enter your wifi SSID: " ssid
		read -p "Enter your wifi password: " wifipass
		nmcli device wifi connect $ssid password $wifipass
		echo ;;
	n|N)
		echo
		echo "Continuing..."
		echo ;;
esac
echo "[ UPDATE SYSTEM ]"
sudo pacman -Syu --noconfirm
echo
echo "[ CONFIGURE TIMEDATECTL ]"
sudo timedatectl set-ntp true
#sudo timedatectl set-local-rtc 1 --adjust-system-clock
echo "----------------------------------------------------------------------"
echo "INSTALL KDE"
echo "----------------------------------------------------------------------"
# Package Info: Don't reinstall|Don't Confirm (y/n)|Disk Partition Utilities  |KDE           |Display Manager         |File Manager|Dialog Viewer|Terminal|User Management|Bluetooth Management          |Power Management|Screen Management|Wallet Management         |KDE Connect     |KDE Info   |KDE RunAsRoot|GTK Management           |Screenshot|View Images|Network + Audio Applets|Default Home Directories|Chrome Integration        |Web Browser|Extract|Display Settings|Latte Dock|SysInfo |Torrent    |PDF   |Media
sudo pacman -S  --needed        --noconfirm         gnome-disk-utility gparted plasma-desktop sddm sddm-kcm xorg-xinit dolphin ark  kdialog       konsole  user-manager    bluedevil pulseaudio-bluetooth powerdevil       kscreen           kwallet-pam kwalletmanager kdeconnect sshfs kinfocenter kdesu         kde-gtk-config breeze-gtk spectacle  gwenview    plasma-nm plasma-pa     xdg-user-dirs            plasma-browser-integration chromium    unzip   xorg-xrandr      latte-dock neofetch qbittorrent okular vlc
# Removed: Wallpapers (plasma-workspace-wallpapers) - Wallpapers aren't that good.
# Removed: Monospace Font (ttf-hack) - Better mono font available.
# Removed: KDE Partition Manager (partitionmanager) - Gnome Disk Utility is better?
# Removed: Kvantum Theme Manager (kvantum-qt5) - Not required for normal usage.
# Removed: Kwrite (kwrite) - Better options available (Sublime).
echo
echo "[ INSTALL PIKAUR: AN AUR HELPER ]"
git clone https://aur.archlinux.org/pikaur.git
cd pikaur
makepkg -fsri --noconfirm
cd /home/$USER
sudo rm -r pikaur
echo
echo "[ INSTALL AUR PACKAGES ]"
# Package Info: Don't reinstall|Don't Confirm (y/n)|Browser Plugin for DRM|Touchpad Gestures|Google Sync
pikaur -S       --needed        --noconfirm         chromium-widevine      libinput-gestures insync
# Not needed: AppImage Launcher (appimagelauncher)
# Not needed: AUR GUI Frontend (pamac-aur)
# Not needed: MacOS like Icon Theme (la-capitaine-icon-theme)
# Not needed: MacOS like Cursor Theme (capitaine-cursors)
# Not needed: Sublime Text - Beta Edition (sublime-text-dev) - Official Arch packages available.
echo
echo "[ ENABLE DISPLAY MANAGER ]"
sudo systemctl enable sddm
echo
echo "[ ENABLE BLUETOOTH ]"
sudo systemctl enable bluetooth
echo
echo "[ CUSTOMIZE TOUCHPAD GESTURES ]"
mkdir -p /home/$USER/.config
touch /home/$USER/.config/libinput-gestures.conf
cat << EOT > /home/$USER/.config/libinput-gestures.conf
# Go to next workspace
#gesture swipe left 3 xdotool set_desktop --relative 1
# Go to previous workspace
#gesture swipe right 3 xdotool set_desktop --relative -- -1
# Go forward
#gesture swipe up 3 xdotool key alt+Right
# Go back
#gesture swipe down 3 xdotool key alt+Left
# Toggle maximize window
#gesture swipe right_up 3 xdotool key super+Page_Up
# Open windows overview
#gesture swipe left_down 3 xdotool key ctrl+F9
# Minimize current window
#gesture swipe left_up 3 xdotool key super+Page_Down
# Open workspaces grid view
#gesture swipe right_down 3 xdotool key ctrl+F8
# Tile window to the right
#gesture pinch clockwise 2 xdotool key super+Right
# Tile window to the left
#gesture pinch anticlockwise 2 xdotool key super+Left
#
# Go forward
gesture swipe up 3 xdotool key alt+Right
# Go back
gesture swipe down 3 xdotool key alt+Left
# Tile window to the left
gesture swipe left 3 xdotool key super+Left
# Tile window to the right
gesture swipe right 3 xdotool key super+Right
# Minimize current window
gesture pinch in 4 xdotool key super+Page_Down
# Toggle maximize window
gesture pinch out 4 xdotool key super+Page_Up
# Go to next workspace
gesture swipe left 4 xdotool set_desktop --relative 1
# Go to previous workspace
gesture swipe right 4 xdotool set_desktop --relative -- -1
# Open windows overview
gesture swipe down 4 xdotool key ctrl+F8
# Open workspaces grid view
gesture swipe up 4 xdotool key ctrl+F9
# Toggle Super # Conflicts with pinch in/out 4
#gesture pinch in 3 xdotool key super
#gesture pinch out 3 xdotool key super
EOT
echo
echo "[ ADD USER TO 'INPUT' GROUP ]"
sudo gpasswd -a $USER input
echo
echo "[ SET APPS TO AUTOSTART ]"
libinput-gestures-setup autostart
mkdir -p /home/$USER/.config/autostart
echo
echo "[ SET SDDM STARTUP SCRIPT ]"
sudo bash -c 'cat << EOT >> /etc/sddm.conf

[X11]
DisplayCommand=/usr/share/sddm/scripts/Xsetup

EOT'
sed -i "s/replaceWithUserNameXsetup/$USER/g" /home/$USER/kdepostinstall
echo
echo "----------------------------------------------------------------------"
echo "SET UP POST INSTALL SCRIPT TO RUN AFTER REBOOT"
echo "----------------------------------------------------------------------"
cat << EOT >> /home/$USER/.config/autostart/runkdepostinstall.desktop
[Desktop Entry]
Type=Application
Version=1.0
Name=kdepostinstall
Exec=/home/$USER/kdepostinstall
Terminal=true
EOT
chmod +x /home/$USER/.config/autostart/runkdepostinstall.desktop
echo
echo "----------------------------------------------------------------------"
echo "REBOOT"
echo "----------------------------------------------------------------------"
sudo reboot
