#!/bin/bash
echo "[ CONFIG - GTK3 - SETTINGS.INI ]"
gtk3Settings="/home/$USER/.config/gtk-3.0/settings.ini"
touch $gtk3Settings
cat << EOT > $gtk3Settings
[Settings]
gtk-application-prefer-dark-theme=false
gtk-button-images=0
gtk-cursor-theme-name=breeze_cursors
gtk-fallback-icon-theme=Adwaita
gtk-font-name=Noto Sans Regular 10
gtk-icon-theme-name=breeze-dark
gtk-menu-images=0
gtk-modules=appmenu-gtk-module
gtk-primary-button-warps-slider=0
gtk-shell-shows-menubar=1
gtk-theme-name=Breeze-Dark
gtk-toolbar-style=GTK_TOOLBAR_ICONS

EOT
echo "[ CONFIG - BREEZERC ]"
configBreezerc="/home/$USER/.config/breezerc"
touch $configBreezerc
cat << EOT > $configBreezerc
[Common]
OutlineCloseButton=false
ShadowSize=ShadowSmall

[Style]
MenuOpacity=30
TabBarDrawCenteredTabs=true
ToolBarDrawItemSeparator=false

[Windeco]
DrawBackgroundGradient=false
DrawBorderOnMaximizedWindows=true
DrawSizeGrip=true

EOT
